spring: 
 profiles:
  active:
  - dev
---
spring:
  profiles: dev
  application:
    name: provider-base
  elasticsearch:
    jest:
      uris:
      - http://123.56.110.16:9200
      read-timeout: 5000
server:
  port: 8078

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@123.57.207.4:7001/eureka,http://root:root@123.57.207.4:7002/eureka
      #defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka

---
spring:
  profiles: test
  application:
    name: provider-base
  elasticsearch:
    jest:
      uris:
      - http://192.168.200.123:9200
      read-timeout: 5000
server:
  port: 8078

eurekaServer:
  host: localhost
  port: 8086
  user: root
  password: root

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port}/eureka
      #defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
            